<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="HerdDesk.Infrastructure.Tests" />
    <InternalsVisibleTo Include="HerdDesk.ContractTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../HerdDesk.Contracts/HerdDesk.Contracts.csproj" />
    <ProjectReference Include="../HerdDesk.Core/HerdDesk.Core.csproj" />
  </ItemGroup>
</Project>
