using HerdDesk.Contracts;

namespace HerdDesk.Terminal.Web;

public sealed record WebMessageValidation(
    bool Accepted,
    string Code,
    string Kind,
    int Version,
    ConnectionEpoch Epoch,
    WebMessageDirection Direction,
    int PayloadBytes,
    InputOrigin? Origin = null,
    ReadOnlyMemory<byte> Bytes = default,
    ulong? Sequence = null,
    bool? Full = null,
    string? Uri = null,
    bool UserGesture = false,
    ushort? Columns = null,
    ushort? Rows = null,
    uint? CellWidthPx = null,
    uint? CellHeightPx = null,
    string? FaultCode = null,
    string? Phase = null,
    string? Token = null,
    string? Text = null,
    string? KeyName = null,
    bool Ctrl = false,
    bool Shift = false,
    bool Alt = false,
    bool AltGr = false,
    bool CapsLock = false,
    string? VisibleText = null,
    string? MouseAction = null,
    int Delta = 0);
